[project]
name = "find_n_points"
version = "0.2.0"
description = ""
requires-python = ">=3.11"
dependencies = [
    "opencv-python",
    "cv_shared @ git+https://github.com/AlexanderAMedvedev/cv_shared.git@0.3.0",
]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
